# Generated by Django 3.2 on 2022-04-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('video_url', models.URLField(max_length=256)),
                ('filename', models.FileField(blank=True, max_length=120, null=True, upload_to='')),
                ('dn_status', models.IntegerField(choices=[(0, 'Not downloaded'), (1, 'In progress'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('dn_last_task_id', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
